import type { AdminModule } from "./admin-types";

const activeSort = [
  { name: "sort_order", label: "Sort", type: "number", parser: "integer", defaultValue: 0 },
  { name: "is_active", label: "Active", type: "checkbox", defaultValue: true },
] as const;

export const adminModules: AdminModule[] = [
  {
    key: "organizations",
    title: "Организации",
    tableName: "organizations",
    description: "Рестораны, адреса, контакты, координаты и расписание.",
    listPath: "/api/v1/organizations",
    createPath: "/api/v1/organizations",
    updatePath: (row) => `/api/v1/organizations/${row.id}`,
    deletePath: (row) => `/api/v1/organizations/${row.id}`,
    idField: "id",
    columns: ["slug", "name", "city", "address", "phone", "photo_url"],
    fields: [
      { name: "slug", label: "Slug", type: "text", required: true },
      { name: "name", label: "Name", type: "text", required: true },
      { name: "city", label: "City", type: "text", required: true },
      { name: "address", label: "Address", type: "text", required: true, wide: true },
      { name: "phone", label: "Phone", type: "text", required: true },
      { name: "intro", label: "Intro", type: "textarea", required: true, wide: true },
      { name: "iiko_api_login", label: "IIKO API login", type: "text", emptyAsNull: true },
      { name: "iiko_organization_id", label: "IIKO organization ID", type: "text", emptyAsNull: true },
      { name: "accepts_pickup", label: "Accepts pickup", type: "checkbox", defaultValue: true },
      { name: "accepts_delivery", label: "Accepts delivery", type: "checkbox", defaultValue: false },
      { name: "is_default_delivery", label: "Default delivery", type: "checkbox", defaultValue: false },
      {
        name: "coordinates",
        label: "Coordinates JSON",
        type: "json",
        required: true,
        wide: true,
        defaultValue: { latitude: 55.751244, longitude: 37.618423 },
        help: "{\"latitude\":55.75,\"longitude\":37.61}",
      },
      {
        name: "working_hours",
        label: "Working hours JSON",
        type: "json",
        required: true,
        wide: true,
        defaultValue: [
          { weekday: 0, opens_at: "10:00:00", closes_at: "22:00:00", is_closed: false },
        ],
        help: "Массив до 7 дней. weekday: 0 понедельник, 6 воскресенье.",
      },
    ],
    uploads: [
      {
        key: "photo",
        label: "Загрузить фото",
        path: (row) => `/api/v1/organizations/${row.id}/photo`,
        fieldName: "photo",
        accept: "image/*",
      },
    ],
    details: [
      { label: "Coordinates", name: "coordinates" },
      { label: "Working hours", name: "working_hours" },
    ],
  },
  {
    key: "booking-categories",
    title: "Категории бронирования",
    tableName: "booking_categories",
    description: "Категории услуг/пространств для бронирования.",
    listPath: "/api/v1/bookings/categories",
    createPath: "/api/v1/bookings/categories",
    updatePath: (row) => `/api/v1/bookings/categories/${row.id}`,
    deletePath: (row) => `/api/v1/bookings/categories/${row.id}`,
    idField: "id",
    columns: ["title", "organization", "description", "sort_order", "is_active"],
    fields: [
      {
        name: "organization_id",
        label: "Organization",
        type: "select",
        required: true,
        relation: { moduleKey: "organizations", labelFields: ["name"] },
      },
      { name: "title", label: "Title", type: "text", required: true },
      { name: "description", label: "Description", type: "textarea", emptyAsNull: true, wide: true },
      ...activeSort,
    ],
    uploads: [
      {
        key: "preview",
        label: "Загрузить preview",
        path: (row) => `/api/v1/bookings/categories/${row.id}/preview`,
        fieldName: "preview",
        accept: "image/*",
      },
    ],
  },
  {
    key: "bookings",
    title: "Бронирования",
    tableName: "bookings",
    description: "Карточки бронирования, изображения и привязка к категориям.",
    listPath: "/api/v1/bookings",
    createPath: "/api/v1/bookings",
    updatePath: (row) => `/api/v1/bookings/${row.id}`,
    deletePath: (row) => `/api/v1/bookings/${row.id}`,
    idField: "id",
    columns: ["title", "organization", "category", "preview_url", "sort_order", "is_active"],
    fields: [
      {
        name: "organization_id",
        label: "Organization",
        type: "select",
        required: true,
        relation: { moduleKey: "organizations", labelFields: ["name"] },
      },
      {
        name: "category_id",
        label: "Category",
        type: "select",
        required: true,
        relation: { moduleKey: "booking-categories", labelFields: ["title"] },
      },
      { name: "title", label: "Title", type: "text", required: true },
      { name: "description", label: "Description", type: "textarea", required: true, wide: true },
      { name: "long_description", label: "Long description", type: "textarea", emptyAsNull: true, wide: true },
      ...activeSort,
    ],
    uploads: [
      {
        key: "preview",
        label: "Загрузить preview",
        path: (row) => `/api/v1/bookings/${row.id}/preview`,
        fieldName: "preview",
        accept: "image/*",
      },
      {
        key: "image",
        label: "Добавить image",
        path: (row) => `/api/v1/bookings/${row.id}/images`,
        fieldName: "image",
        accept: "image/*",
        extraFields: [
          {
            name: "orientation",
            label: "Orientation",
            type: "select",
            defaultValue: "horizontal",
            options: [
              { label: "horizontal", value: "horizontal" },
              { label: "vertical", value: "vertical" },
            ],
          },
          { name: "alt_text", label: "Alt text", type: "text", emptyAsNull: true },
          { name: "sort_order", label: "Sort", type: "number", parser: "integer", defaultValue: 0 },
        ],
      },
      {
        key: "images",
        label: "Добавить images bulk",
        path: (row) => `/api/v1/bookings/${row.id}/images/bulk`,
        fieldName: "images",
        multiple: true,
        accept: "image/*",
        extraFields: [
          {
            name: "orientation",
            label: "Orientation",
            type: "select",
            defaultValue: "horizontal",
            options: [
              { label: "horizontal", value: "horizontal" },
              { label: "vertical", value: "vertical" },
            ],
          },
          { name: "sort_order", label: "Sort from", type: "number", parser: "integer", defaultValue: 0 },
        ],
      },
    ],
    details: [{ label: "Images", name: "images" }],
  },
  {
    key: "delivery-zones",
    title: "Зоны доставки",
    tableName: "delivery_zones",
    description: "Дистанции, минимальный заказ и цена доставки.",
    listPath: "/api/v1/delivery-zones/admin",
    createPath: "/api/v1/delivery-zones",
    updatePath: (row) => `/api/v1/delivery-zones/${row.id}`,
    deletePath: (row) => `/api/v1/delivery-zones/${row.id}`,
    idField: "id",
    columns: ["distance_from_km", "distance_to_km", "min_order_amount", "price"],
    fields: [
      { name: "distance_from_km", label: "From km", type: "number", required: true, parser: "number" },
      { name: "distance_to_km", label: "To km", type: "number", required: true, parser: "number" },
      { name: "min_order_amount", label: "Min order", type: "number", parser: "integer", emptyAsNull: true },
      { name: "price", label: "Price", type: "number", required: true, parser: "integer" },
    ],
  },
  {
    key: "menu-items",
    title: "Menu items",
    tableName: "menu_item_content",
    description: "Admin content overrides for menu items and their images.",
    listPath: "/api/v1/menu/admin/items",
    createPath: "/api/v1/menu/admin/items",
    updatePath: (row) => `/api/v1/menu/admin/items/${row.id}`,
    deletePath: (row) => `/api/v1/menu/admin/items/${row.id}`,
    idField: "id",
    columns: ["sku", "iiko_item_id", "name_override", "description", "image_url", "sort_order", "is_active"],
    fields: [
      { name: "iiko_item_id", label: "IIKO item ID", type: "text", emptyAsNull: true },
      { name: "sku", label: "SKU", type: "text", emptyAsNull: true },
      { name: "name_override", label: "Name override", type: "text", emptyAsNull: true },
      { name: "description", label: "Description", type: "textarea", emptyAsNull: true, wide: true },
      ...activeSort,
    ],
    uploads: [
      {
        key: "image",
        label: "Загрузить image",
        path: (row) => `/api/v1/menu/admin/items/${row.id}/image`,
        fieldName: "image",
        accept: "image/*",
      },
    ],
  },
  {
    key: "stories",
    title: "Истории",
    tableName: "stories",
    description: "Сторис и слайды для витрины.",
    listPath: "/api/v1/stories/admin/all",
    createPath: "/api/v1/stories",
    updatePath: (row) => `/api/v1/stories/${row.id}`,
    deletePath: (row) => `/api/v1/stories/${row.id}`,
    idField: "id",
    columns: ["slug", "title", "previewImage", "sort_order", "is_active"],
    fields: [
      { name: "slug", label: "Slug", type: "text", required: true },
      { name: "title", label: "Title", type: "text", required: true },
      { name: "description", label: "Description", type: "textarea", emptyAsNull: true, wide: true },
      ...activeSort,
    ],
    uploads: [
      {
        key: "preview",
        label: "Загрузить preview",
        path: (row) => `/api/v1/stories/${row.id}/preview`,
        fieldName: "preview",
        accept: "image/*",
      },
    ],
    details: [{ label: "Slides", name: "slides" }],
    supportsStorySlides: true,
  },
];
